// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salary34000.Data;

#nullable disable

namespace Salary34000.Migrations
{
    [DbContext(typeof(SalaryContext))]
    [Migration("20230221114819_ExperimentScore")]
    partial class ExperimentScore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Salary34000.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "زیر دیپلم",
                            Score = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "دیپلم",
                            Score = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "فوق دیپلم",
                            Score = 6
                        },
                        new
                        {
                            Id = 4,
                            Description = "کارشناسی",
                            Score = 8
                        },
                        new
                        {
                            Id = 5,
                            Description = "کارشناسی ارشد",
                            Score = 10
                        },
                        new
                        {
                            Id = 6,
                            Description = "دکتری",
                            Score = 10
                        });
                });

            modelBuilder.Entity("Salary34000.Models.EducationRelationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EducationRelationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coefficient = 1.0,
                            Description = "مرتبط"
                        },
                        new
                        {
                            Id = 2,
                            Coefficient = 0.84999999999999998,
                            Description = "نیمه مرتبط"
                        },
                        new
                        {
                            Id = 3,
                            Coefficient = 0.69999999999999996,
                            Description = "غیر مرتبط"
                        });
                });

            modelBuilder.Entity("Salary34000.Models.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmploymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "رسمی"
                        },
                        new
                        {
                            Id = 2,
                            Description = "قرارداد پاره‌وقت"
                        },
                        new
                        {
                            Id = 3,
                            Description = "قرارداد تمام‌وقت"
                        });
                });

            modelBuilder.Entity("Salary34000.Models.ExperienceScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessionalPathId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalPathId");

                    b.ToTable("ExperienceScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProfessionalPathId = 1,
                            Score = 25.0,
                            WorkExperience = 0
                        },
                        new
                        {
                            Id = 2,
                            ProfessionalPathId = 1,
                            Score = 25.0,
                            WorkExperience = 1
                        },
                        new
                        {
                            Id = 3,
                            ProfessionalPathId = 1,
                            Score = 25.17241379,
                            WorkExperience = 2
                        },
                        new
                        {
                            Id = 4,
                            ProfessionalPathId = 1,
                            Score = 25.344827590000001,
                            WorkExperience = 3
                        },
                        new
                        {
                            Id = 5,
                            ProfessionalPathId = 1,
                            Score = 25.517241380000002,
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 6,
                            ProfessionalPathId = 1,
                            Score = 25.689655170000002,
                            WorkExperience = 5
                        },
                        new
                        {
                            Id = 7,
                            ProfessionalPathId = 1,
                            Score = 25.862068969999999,
                            WorkExperience = 6
                        },
                        new
                        {
                            Id = 8,
                            ProfessionalPathId = 1,
                            Score = 26.03448276,
                            WorkExperience = 7
                        },
                        new
                        {
                            Id = 9,
                            ProfessionalPathId = 1,
                            Score = 26.20689655,
                            WorkExperience = 8
                        },
                        new
                        {
                            Id = 10,
                            ProfessionalPathId = 1,
                            Score = 26.37931034,
                            WorkExperience = 9
                        },
                        new
                        {
                            Id = 11,
                            ProfessionalPathId = 1,
                            Score = 26.551724140000001,
                            WorkExperience = 10
                        },
                        new
                        {
                            Id = 12,
                            ProfessionalPathId = 1,
                            Score = 26.724137930000001,
                            WorkExperience = 11
                        },
                        new
                        {
                            Id = 13,
                            ProfessionalPathId = 1,
                            Score = 26.896551720000001,
                            WorkExperience = 12
                        },
                        new
                        {
                            Id = 14,
                            ProfessionalPathId = 1,
                            Score = 27.068965519999999,
                            WorkExperience = 13
                        },
                        new
                        {
                            Id = 15,
                            ProfessionalPathId = 1,
                            Score = 27.241379309999999,
                            WorkExperience = 14
                        },
                        new
                        {
                            Id = 16,
                            ProfessionalPathId = 1,
                            Score = 27.413793099999999,
                            WorkExperience = 15
                        },
                        new
                        {
                            Id = 17,
                            ProfessionalPathId = 1,
                            Score = 27.586206900000001,
                            WorkExperience = 16
                        },
                        new
                        {
                            Id = 18,
                            ProfessionalPathId = 1,
                            Score = 27.758620690000001,
                            WorkExperience = 17
                        },
                        new
                        {
                            Id = 19,
                            ProfessionalPathId = 1,
                            Score = 27.931034480000001,
                            WorkExperience = 18
                        },
                        new
                        {
                            Id = 20,
                            ProfessionalPathId = 1,
                            Score = 28.103448279999999,
                            WorkExperience = 19
                        },
                        new
                        {
                            Id = 21,
                            ProfessionalPathId = 1,
                            Score = 28.275862069999999,
                            WorkExperience = 20
                        },
                        new
                        {
                            Id = 22,
                            ProfessionalPathId = 1,
                            Score = 28.448275859999999,
                            WorkExperience = 21
                        },
                        new
                        {
                            Id = 23,
                            ProfessionalPathId = 1,
                            Score = 28.62068966,
                            WorkExperience = 22
                        },
                        new
                        {
                            Id = 24,
                            ProfessionalPathId = 1,
                            Score = 28.79310345,
                            WorkExperience = 23
                        },
                        new
                        {
                            Id = 25,
                            ProfessionalPathId = 1,
                            Score = 28.96551724,
                            WorkExperience = 24
                        },
                        new
                        {
                            Id = 26,
                            ProfessionalPathId = 1,
                            Score = 29.137931030000001,
                            WorkExperience = 25
                        },
                        new
                        {
                            Id = 27,
                            ProfessionalPathId = 1,
                            Score = 29.310344829999998,
                            WorkExperience = 26
                        },
                        new
                        {
                            Id = 28,
                            ProfessionalPathId = 1,
                            Score = 29.482758619999998,
                            WorkExperience = 27
                        },
                        new
                        {
                            Id = 29,
                            ProfessionalPathId = 1,
                            Score = 29.655172409999999,
                            WorkExperience = 28
                        },
                        new
                        {
                            Id = 30,
                            ProfessionalPathId = 1,
                            Score = 29.82758621,
                            WorkExperience = 29
                        },
                        new
                        {
                            Id = 31,
                            ProfessionalPathId = 1,
                            Score = 30.0,
                            WorkExperience = 30
                        },
                        new
                        {
                            Id = 32,
                            ProfessionalPathId = 2,
                            Score = 20.0,
                            WorkExperience = 0
                        },
                        new
                        {
                            Id = 33,
                            ProfessionalPathId = 2,
                            Score = 20.0,
                            WorkExperience = 1
                        },
                        new
                        {
                            Id = 34,
                            ProfessionalPathId = 2,
                            Score = 20.17241379,
                            WorkExperience = 2
                        },
                        new
                        {
                            Id = 35,
                            ProfessionalPathId = 2,
                            Score = 20.344827590000001,
                            WorkExperience = 3
                        },
                        new
                        {
                            Id = 36,
                            ProfessionalPathId = 2,
                            Score = 20.517241380000002,
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 37,
                            ProfessionalPathId = 2,
                            Score = 20.689655170000002,
                            WorkExperience = 5
                        },
                        new
                        {
                            Id = 38,
                            ProfessionalPathId = 2,
                            Score = 20.862068969999999,
                            WorkExperience = 6
                        },
                        new
                        {
                            Id = 39,
                            ProfessionalPathId = 2,
                            Score = 21.03448276,
                            WorkExperience = 7
                        },
                        new
                        {
                            Id = 40,
                            ProfessionalPathId = 2,
                            Score = 21.20689655,
                            WorkExperience = 8
                        },
                        new
                        {
                            Id = 41,
                            ProfessionalPathId = 2,
                            Score = 21.37931034,
                            WorkExperience = 9
                        },
                        new
                        {
                            Id = 42,
                            ProfessionalPathId = 2,
                            Score = 21.551724140000001,
                            WorkExperience = 10
                        },
                        new
                        {
                            Id = 43,
                            ProfessionalPathId = 2,
                            Score = 21.724137930000001,
                            WorkExperience = 11
                        },
                        new
                        {
                            Id = 44,
                            ProfessionalPathId = 2,
                            Score = 21.896551720000001,
                            WorkExperience = 12
                        },
                        new
                        {
                            Id = 45,
                            ProfessionalPathId = 2,
                            Score = 22.068965519999999,
                            WorkExperience = 13
                        },
                        new
                        {
                            Id = 46,
                            ProfessionalPathId = 2,
                            Score = 22.241379309999999,
                            WorkExperience = 14
                        },
                        new
                        {
                            Id = 47,
                            ProfessionalPathId = 2,
                            Score = 22.413793099999999,
                            WorkExperience = 15
                        },
                        new
                        {
                            Id = 48,
                            ProfessionalPathId = 2,
                            Score = 22.586206900000001,
                            WorkExperience = 16
                        },
                        new
                        {
                            Id = 49,
                            ProfessionalPathId = 2,
                            Score = 22.758620690000001,
                            WorkExperience = 17
                        },
                        new
                        {
                            Id = 50,
                            ProfessionalPathId = 2,
                            Score = 22.931034480000001,
                            WorkExperience = 18
                        },
                        new
                        {
                            Id = 51,
                            ProfessionalPathId = 2,
                            Score = 23.103448279999999,
                            WorkExperience = 19
                        },
                        new
                        {
                            Id = 52,
                            ProfessionalPathId = 2,
                            Score = 23.275862069999999,
                            WorkExperience = 20
                        },
                        new
                        {
                            Id = 53,
                            ProfessionalPathId = 2,
                            Score = 23.448275859999999,
                            WorkExperience = 21
                        },
                        new
                        {
                            Id = 54,
                            ProfessionalPathId = 2,
                            Score = 23.62068966,
                            WorkExperience = 22
                        },
                        new
                        {
                            Id = 55,
                            ProfessionalPathId = 2,
                            Score = 23.79310345,
                            WorkExperience = 23
                        },
                        new
                        {
                            Id = 56,
                            ProfessionalPathId = 2,
                            Score = 23.96551724,
                            WorkExperience = 24
                        },
                        new
                        {
                            Id = 57,
                            ProfessionalPathId = 2,
                            Score = 24.137931030000001,
                            WorkExperience = 25
                        },
                        new
                        {
                            Id = 58,
                            ProfessionalPathId = 2,
                            Score = 24.310344829999998,
                            WorkExperience = 26
                        },
                        new
                        {
                            Id = 59,
                            ProfessionalPathId = 2,
                            Score = 24.482758619999998,
                            WorkExperience = 27
                        },
                        new
                        {
                            Id = 60,
                            ProfessionalPathId = 2,
                            Score = 24.655172409999999,
                            WorkExperience = 28
                        },
                        new
                        {
                            Id = 61,
                            ProfessionalPathId = 2,
                            Score = 24.82758621,
                            WorkExperience = 29
                        },
                        new
                        {
                            Id = 62,
                            ProfessionalPathId = 2,
                            Score = 25.0,
                            WorkExperience = 30
                        },
                        new
                        {
                            Id = 63,
                            ProfessionalPathId = 3,
                            Score = 15.0,
                            WorkExperience = 0
                        },
                        new
                        {
                            Id = 64,
                            ProfessionalPathId = 3,
                            Score = 15.0,
                            WorkExperience = 1
                        },
                        new
                        {
                            Id = 65,
                            ProfessionalPathId = 3,
                            Score = 15.17241379,
                            WorkExperience = 2
                        },
                        new
                        {
                            Id = 66,
                            ProfessionalPathId = 3,
                            Score = 15.34482759,
                            WorkExperience = 3
                        },
                        new
                        {
                            Id = 67,
                            ProfessionalPathId = 3,
                            Score = 15.51724138,
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 68,
                            ProfessionalPathId = 3,
                            Score = 15.68965517,
                            WorkExperience = 5
                        },
                        new
                        {
                            Id = 69,
                            ProfessionalPathId = 3,
                            Score = 15.862068969999999,
                            WorkExperience = 6
                        },
                        new
                        {
                            Id = 70,
                            ProfessionalPathId = 3,
                            Score = 16.03448276,
                            WorkExperience = 7
                        },
                        new
                        {
                            Id = 71,
                            ProfessionalPathId = 3,
                            Score = 16.20689655,
                            WorkExperience = 8
                        },
                        new
                        {
                            Id = 72,
                            ProfessionalPathId = 3,
                            Score = 16.37931034,
                            WorkExperience = 9
                        },
                        new
                        {
                            Id = 73,
                            ProfessionalPathId = 3,
                            Score = 16.551724140000001,
                            WorkExperience = 10
                        },
                        new
                        {
                            Id = 74,
                            ProfessionalPathId = 3,
                            Score = 16.724137930000001,
                            WorkExperience = 11
                        },
                        new
                        {
                            Id = 75,
                            ProfessionalPathId = 3,
                            Score = 16.896551720000001,
                            WorkExperience = 12
                        },
                        new
                        {
                            Id = 76,
                            ProfessionalPathId = 3,
                            Score = 17.068965519999999,
                            WorkExperience = 13
                        },
                        new
                        {
                            Id = 77,
                            ProfessionalPathId = 3,
                            Score = 17.241379309999999,
                            WorkExperience = 14
                        },
                        new
                        {
                            Id = 78,
                            ProfessionalPathId = 3,
                            Score = 17.413793099999999,
                            WorkExperience = 15
                        },
                        new
                        {
                            Id = 79,
                            ProfessionalPathId = 3,
                            Score = 17.586206900000001,
                            WorkExperience = 16
                        },
                        new
                        {
                            Id = 80,
                            ProfessionalPathId = 3,
                            Score = 17.758620690000001,
                            WorkExperience = 17
                        },
                        new
                        {
                            Id = 81,
                            ProfessionalPathId = 3,
                            Score = 17.931034480000001,
                            WorkExperience = 18
                        },
                        new
                        {
                            Id = 82,
                            ProfessionalPathId = 3,
                            Score = 18.103448279999999,
                            WorkExperience = 19
                        },
                        new
                        {
                            Id = 83,
                            ProfessionalPathId = 3,
                            Score = 18.275862069999999,
                            WorkExperience = 20
                        },
                        new
                        {
                            Id = 84,
                            ProfessionalPathId = 3,
                            Score = 18.448275859999999,
                            WorkExperience = 21
                        },
                        new
                        {
                            Id = 85,
                            ProfessionalPathId = 3,
                            Score = 18.62068966,
                            WorkExperience = 22
                        },
                        new
                        {
                            Id = 86,
                            ProfessionalPathId = 3,
                            Score = 18.79310345,
                            WorkExperience = 23
                        },
                        new
                        {
                            Id = 87,
                            ProfessionalPathId = 3,
                            Score = 18.96551724,
                            WorkExperience = 24
                        },
                        new
                        {
                            Id = 88,
                            ProfessionalPathId = 3,
                            Score = 19.137931030000001,
                            WorkExperience = 25
                        },
                        new
                        {
                            Id = 89,
                            ProfessionalPathId = 3,
                            Score = 19.310344829999998,
                            WorkExperience = 26
                        },
                        new
                        {
                            Id = 90,
                            ProfessionalPathId = 3,
                            Score = 19.482758619999998,
                            WorkExperience = 27
                        },
                        new
                        {
                            Id = 91,
                            ProfessionalPathId = 3,
                            Score = 19.655172409999999,
                            WorkExperience = 28
                        },
                        new
                        {
                            Id = 92,
                            ProfessionalPathId = 3,
                            Score = 19.82758621,
                            WorkExperience = 29
                        },
                        new
                        {
                            Id = 93,
                            ProfessionalPathId = 3,
                            Score = 20.0,
                            WorkExperience = 30
                        },
                        new
                        {
                            Id = 94,
                            ProfessionalPathId = 4,
                            Score = 10.0,
                            WorkExperience = 0
                        },
                        new
                        {
                            Id = 95,
                            ProfessionalPathId = 4,
                            Score = 10.0,
                            WorkExperience = 1
                        },
                        new
                        {
                            Id = 96,
                            ProfessionalPathId = 4,
                            Score = 10.17241379,
                            WorkExperience = 2
                        },
                        new
                        {
                            Id = 97,
                            ProfessionalPathId = 4,
                            Score = 10.34482759,
                            WorkExperience = 3
                        },
                        new
                        {
                            Id = 98,
                            ProfessionalPathId = 4,
                            Score = 10.51724138,
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 99,
                            ProfessionalPathId = 4,
                            Score = 10.68965517,
                            WorkExperience = 5
                        },
                        new
                        {
                            Id = 100,
                            ProfessionalPathId = 4,
                            Score = 10.862068969999999,
                            WorkExperience = 6
                        },
                        new
                        {
                            Id = 101,
                            ProfessionalPathId = 4,
                            Score = 11.03448276,
                            WorkExperience = 7
                        },
                        new
                        {
                            Id = 102,
                            ProfessionalPathId = 4,
                            Score = 11.20689655,
                            WorkExperience = 8
                        },
                        new
                        {
                            Id = 103,
                            ProfessionalPathId = 4,
                            Score = 11.37931034,
                            WorkExperience = 9
                        },
                        new
                        {
                            Id = 104,
                            ProfessionalPathId = 4,
                            Score = 11.551724139999999,
                            WorkExperience = 10
                        },
                        new
                        {
                            Id = 105,
                            ProfessionalPathId = 4,
                            Score = 11.724137929999999,
                            WorkExperience = 11
                        },
                        new
                        {
                            Id = 106,
                            ProfessionalPathId = 4,
                            Score = 11.89655172,
                            WorkExperience = 12
                        },
                        new
                        {
                            Id = 107,
                            ProfessionalPathId = 4,
                            Score = 12.068965520000001,
                            WorkExperience = 13
                        },
                        new
                        {
                            Id = 108,
                            ProfessionalPathId = 4,
                            Score = 12.241379309999999,
                            WorkExperience = 14
                        },
                        new
                        {
                            Id = 109,
                            ProfessionalPathId = 4,
                            Score = 12.413793099999999,
                            WorkExperience = 15
                        },
                        new
                        {
                            Id = 110,
                            ProfessionalPathId = 4,
                            Score = 12.586206900000001,
                            WorkExperience = 16
                        },
                        new
                        {
                            Id = 111,
                            ProfessionalPathId = 4,
                            Score = 12.758620690000001,
                            WorkExperience = 17
                        },
                        new
                        {
                            Id = 112,
                            ProfessionalPathId = 4,
                            Score = 12.931034479999999,
                            WorkExperience = 18
                        },
                        new
                        {
                            Id = 113,
                            ProfessionalPathId = 4,
                            Score = 13.10344828,
                            WorkExperience = 19
                        },
                        new
                        {
                            Id = 114,
                            ProfessionalPathId = 4,
                            Score = 13.275862070000001,
                            WorkExperience = 20
                        },
                        new
                        {
                            Id = 115,
                            ProfessionalPathId = 4,
                            Score = 13.448275860000001,
                            WorkExperience = 21
                        },
                        new
                        {
                            Id = 116,
                            ProfessionalPathId = 4,
                            Score = 13.62068966,
                            WorkExperience = 22
                        },
                        new
                        {
                            Id = 117,
                            ProfessionalPathId = 4,
                            Score = 13.79310345,
                            WorkExperience = 23
                        },
                        new
                        {
                            Id = 118,
                            ProfessionalPathId = 4,
                            Score = 13.96551724,
                            WorkExperience = 24
                        },
                        new
                        {
                            Id = 119,
                            ProfessionalPathId = 4,
                            Score = 14.137931030000001,
                            WorkExperience = 25
                        },
                        new
                        {
                            Id = 120,
                            ProfessionalPathId = 4,
                            Score = 14.31034483,
                            WorkExperience = 26
                        },
                        new
                        {
                            Id = 121,
                            ProfessionalPathId = 4,
                            Score = 14.48275862,
                            WorkExperience = 27
                        },
                        new
                        {
                            Id = 122,
                            ProfessionalPathId = 4,
                            Score = 14.65517241,
                            WorkExperience = 28
                        },
                        new
                        {
                            Id = 123,
                            ProfessionalPathId = 4,
                            Score = 14.82758621,
                            WorkExperience = 29
                        },
                        new
                        {
                            Id = 124,
                            ProfessionalPathId = 4,
                            Score = 15.0,
                            WorkExperience = 30
                        },
                        new
                        {
                            Id = 125,
                            ProfessionalPathId = 5,
                            Score = 5.0,
                            WorkExperience = 0
                        },
                        new
                        {
                            Id = 126,
                            ProfessionalPathId = 5,
                            Score = 5.0,
                            WorkExperience = 1
                        },
                        new
                        {
                            Id = 127,
                            ProfessionalPathId = 5,
                            Score = 5.1724137929999996,
                            WorkExperience = 2
                        },
                        new
                        {
                            Id = 128,
                            ProfessionalPathId = 5,
                            Score = 5.3448275860000001,
                            WorkExperience = 3
                        },
                        new
                        {
                            Id = 129,
                            ProfessionalPathId = 5,
                            Score = 5.5172413789999997,
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 130,
                            ProfessionalPathId = 5,
                            Score = 5.6896551720000001,
                            WorkExperience = 5
                        },
                        new
                        {
                            Id = 131,
                            ProfessionalPathId = 5,
                            Score = 5.8620689659999998,
                            WorkExperience = 6
                        },
                        new
                        {
                            Id = 132,
                            ProfessionalPathId = 5,
                            Score = 6.0344827590000003,
                            WorkExperience = 7
                        },
                        new
                        {
                            Id = 133,
                            ProfessionalPathId = 5,
                            Score = 6.2068965519999999,
                            WorkExperience = 8
                        },
                        new
                        {
                            Id = 134,
                            ProfessionalPathId = 5,
                            Score = 6.3793103450000004,
                            WorkExperience = 9
                        },
                        new
                        {
                            Id = 135,
                            ProfessionalPathId = 5,
                            Score = 6.551724138,
                            WorkExperience = 10
                        },
                        new
                        {
                            Id = 136,
                            ProfessionalPathId = 5,
                            Score = 6.7241379309999996,
                            WorkExperience = 11
                        },
                        new
                        {
                            Id = 137,
                            ProfessionalPathId = 5,
                            Score = 6.896551724,
                            WorkExperience = 12
                        },
                        new
                        {
                            Id = 138,
                            ProfessionalPathId = 5,
                            Score = 7.0689655169999996,
                            WorkExperience = 13
                        },
                        new
                        {
                            Id = 139,
                            ProfessionalPathId = 5,
                            Score = 7.2413793100000001,
                            WorkExperience = 14
                        },
                        new
                        {
                            Id = 140,
                            ProfessionalPathId = 5,
                            Score = 7.4137931029999997,
                            WorkExperience = 15
                        },
                        new
                        {
                            Id = 141,
                            ProfessionalPathId = 5,
                            Score = 7.5862068970000003,
                            WorkExperience = 16
                        },
                        new
                        {
                            Id = 142,
                            ProfessionalPathId = 5,
                            Score = 7.7586206899999999,
                            WorkExperience = 17
                        },
                        new
                        {
                            Id = 143,
                            ProfessionalPathId = 5,
                            Score = 7.9310344830000004,
                            WorkExperience = 18
                        },
                        new
                        {
                            Id = 144,
                            ProfessionalPathId = 5,
                            Score = 8.103448276,
                            WorkExperience = 19
                        },
                        new
                        {
                            Id = 145,
                            ProfessionalPathId = 5,
                            Score = 8.2758620690000004,
                            WorkExperience = 20
                        },
                        new
                        {
                            Id = 146,
                            ProfessionalPathId = 5,
                            Score = 8.4482758619999991,
                            WorkExperience = 21
                        },
                        new
                        {
                            Id = 147,
                            ProfessionalPathId = 5,
                            Score = 8.6206896549999996,
                            WorkExperience = 22
                        },
                        new
                        {
                            Id = 148,
                            ProfessionalPathId = 5,
                            Score = 8.7931034480000001,
                            WorkExperience = 23
                        },
                        new
                        {
                            Id = 149,
                            ProfessionalPathId = 5,
                            Score = 8.9655172410000006,
                            WorkExperience = 24
                        },
                        new
                        {
                            Id = 150,
                            ProfessionalPathId = 5,
                            Score = 9.1379310339999993,
                            WorkExperience = 25
                        },
                        new
                        {
                            Id = 151,
                            ProfessionalPathId = 5,
                            Score = 9.3103448279999999,
                            WorkExperience = 26
                        },
                        new
                        {
                            Id = 152,
                            ProfessionalPathId = 5,
                            Score = 9.4827586210000003,
                            WorkExperience = 27
                        },
                        new
                        {
                            Id = 153,
                            ProfessionalPathId = 5,
                            Score = 9.6551724140000008,
                            WorkExperience = 28
                        },
                        new
                        {
                            Id = 154,
                            ProfessionalPathId = 5,
                            Score = 9.8275862069999995,
                            WorkExperience = 29
                        },
                        new
                        {
                            Id = 155,
                            ProfessionalPathId = 5,
                            Score = 10.0,
                            WorkExperience = 30
                        });
                });

            modelBuilder.Entity("Salary34000.Models.JobGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "10"
                        },
                        new
                        {
                            Id = 11,
                            Description = "11"
                        },
                        new
                        {
                            Id = 12,
                            Description = "12"
                        },
                        new
                        {
                            Id = 13,
                            Description = "13"
                        },
                        new
                        {
                            Id = 14,
                            Description = "14"
                        },
                        new
                        {
                            Id = 15,
                            Description = "15"
                        },
                        new
                        {
                            Id = 16,
                            Description = "16"
                        },
                        new
                        {
                            Id = 17,
                            Description = "17"
                        },
                        new
                        {
                            Id = 18,
                            Description = "18"
                        },
                        new
                        {
                            Id = 19,
                            Description = "19"
                        },
                        new
                        {
                            Id = 20,
                            Description = "20"
                        },
                        new
                        {
                            Id = 21,
                            Description = "A"
                        },
                        new
                        {
                            Id = 22,
                            Description = "B"
                        },
                        new
                        {
                            Id = 23,
                            Description = "C"
                        },
                        new
                        {
                            Id = 24,
                            Description = "D"
                        },
                        new
                        {
                            Id = 25,
                            Description = "E"
                        });
                });

            modelBuilder.Entity("Salary34000.Models.MilitaryService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MilitaryServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "پروژه نخبه وظیفه"
                        },
                        new
                        {
                            Id = 2,
                            Description = "در حال انجام"
                        },
                        new
                        {
                            Id = 3,
                            Description = "کارت پایان خدمت"
                        },
                        new
                        {
                            Id = 4,
                            Description = "کارت معافیت "
                        },
                        new
                        {
                            Id = 5,
                            Description = "معافیت پزشکی"
                        },
                        new
                        {
                            Id = 6,
                            Description = "معافیت تحصیلی"
                        },
                        new
                        {
                            Id = 7,
                            Description = "معافیت دائم"
                        },
                        new
                        {
                            Id = 8,
                            Description = "معافیت زیر پرچم"
                        },
                        new
                        {
                            Id = 9,
                            Description = "معافیت کفالت"
                        },
                        new
                        {
                            Id = 10,
                            Description = "معافیت موارد خاص"
                        });
                });

            modelBuilder.Entity("Salary34000.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Occupations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coefficient = 2.7999999999999998,
                            Description = "صف تخصصی - فنی"
                        },
                        new
                        {
                            Id = 2,
                            Coefficient = 2.0,
                            Description = "صف تخصصی - فنی 1"
                        },
                        new
                        {
                            Id = 3,
                            Coefficient = 1.5,
                            Description = "صف تخصصی - فنی 2"
                        },
                        new
                        {
                            Id = 4,
                            Coefficient = 1.2,
                            Description = "صف تخصصی - فنی 3"
                        },
                        new
                        {
                            Id = 5,
                            Coefficient = 2.5,
                            Description = "صف تخصصی - پشتیبانی"
                        },
                        new
                        {
                            Id = 6,
                            Coefficient = 1.7,
                            Description = "صف تخصصی - پشتیبانی 1"
                        },
                        new
                        {
                            Id = 7,
                            Coefficient = 1.25,
                            Description = "صف تخصصی - پشتیبانی 2"
                        },
                        new
                        {
                            Id = 8,
                            Coefficient = 1.2,
                            Description = "صف تخصصی - پشتیبانی 3"
                        },
                        new
                        {
                            Id = 9,
                            Coefficient = 1.1000000000000001,
                            Description = "ستاد تخصصی"
                        },
                        new
                        {
                            Id = 10,
                            Coefficient = 1.05,
                            Description = "ستاد پشتیبانی"
                        },
                        new
                        {
                            Id = 11,
                            Coefficient = 1.0,
                            Description = "ستاد خدماتی"
                        });
                });

            modelBuilder.Entity("Salary34000.Models.OrganizationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrganizationUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "مدیریت پشتیبانی و خدمات"
                        },
                        new
                        {
                            Id = 2,
                            Description = "حوزه مدیر عامل"
                        },
                        new
                        {
                            Id = 3,
                            Description = "مدیریت حراست"
                        },
                        new
                        {
                            Id = 4,
                            Description = "مدیریت تدارکات"
                        },
                        new
                        {
                            Id = 5,
                            Description = "گروه فناوین"
                        },
                        new
                        {
                            Id = 6,
                            Description = "گروه پایش"
                        },
                        new
                        {
                            Id = 7,
                            Description = "گروه جم"
                        },
                        new
                        {
                            Id = 8,
                            Description = "گروه ارگ"
                        },
                        new
                        {
                            Id = 9,
                            Description = "گروه حافظ"
                        },
                        new
                        {
                            Id = 10,
                            Description = "مدیریت منابع انسانی "
                        },
                        new
                        {
                            Id = 11,
                            Description = "مدیریت مالی"
                        },
                        new
                        {
                            Id = 12,
                            Description = "گروه بصیر"
                        },
                        new
                        {
                            Id = 13,
                            Description = "مدیریت بازرگانی"
                        },
                        new
                        {
                            Id = 14,
                            Description = "گروه آفاق"
                        },
                        new
                        {
                            Id = 15,
                            Description = "مدیریت برنامه ریزی و نظارت"
                        },
                        new
                        {
                            Id = 16,
                            Description = "گروه فناوری و شتابدهی برنا"
                        },
                        new
                        {
                            Id = 17,
                            Description = "شیخ بهایی"
                        },
                        new
                        {
                            Id = 18,
                            Description = "گروه پویش"
                        },
                        new
                        {
                            Id = 19,
                            Description = "گروه ماهان"
                        },
                        new
                        {
                            Id = 20,
                            Description = "مدیریت فاوا"
                        },
                        new
                        {
                            Id = 21,
                            Description = "مدیریت تدارکات"
                        });
                });

            modelBuilder.Entity("Salary34000.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConsolidatedInsurance")
                        .HasColumnType("REAL");

                    b.Property<string>("DocumentCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentSerial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EducationAverage")
                        .HasColumnType("REAL");

                    b.Property<string>("EducationField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EducationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EducationRelationStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmploymentEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmploymentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MarriageDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MilitaryServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OldBaseSummery")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OldHokmSummery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizationPost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonelCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessionalPathId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SuperCollectable")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.HasIndex("EducationRelationStatusId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("JobGroupId");

                    b.HasIndex("MilitaryServiceId");

                    b.HasIndex("OccupationId");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("ProfessionalPathId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Salary34000.Models.ProfessionalPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProfessionalPaths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 33218504L,
                            Coefficient = 1.0,
                            Description = "مدیریتی"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 16609252L,
                            Coefficient = 0.5,
                            Description = "کارشناسی"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 11072835L,
                            Coefficient = 0.33000000000000002,
                            Description = "کاردانی"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 8304626L,
                            Coefficient = 0.25,
                            Description = "کارمندی"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 6643701L,
                            Coefficient = 0.20000000000000001,
                            Description = "کارگری"
                        });
                });

            modelBuilder.Entity("Salary34000.Models.ExperienceScore", b =>
                {
                    b.HasOne("Salary34000.Models.ProfessionalPath", "ProfessionalPath")
                        .WithMany()
                        .HasForeignKey("ProfessionalPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalPath");
                });

            modelBuilder.Entity("Salary34000.Models.Person", b =>
                {
                    b.HasOne("Salary34000.Models.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary34000.Models.EducationRelationStatus", "EducationRelationStatus")
                        .WithMany()
                        .HasForeignKey("EducationRelationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary34000.Models.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary34000.Models.JobGroup", "JobGroup")
                        .WithMany()
                        .HasForeignKey("JobGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary34000.Models.MilitaryService", "MilitaryService")
                        .WithMany()
                        .HasForeignKey("MilitaryServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary34000.Models.Occupation", "Occupation")
                        .WithMany()
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary34000.Models.OrganizationUnit", "OrganizationUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary34000.Models.ProfessionalPath", "ProfessionalPath")
                        .WithMany()
                        .HasForeignKey("ProfessionalPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");

                    b.Navigation("EducationRelationStatus");

                    b.Navigation("EmploymentType");

                    b.Navigation("JobGroup");

                    b.Navigation("MilitaryService");

                    b.Navigation("Occupation");

                    b.Navigation("OrganizationUnit");

                    b.Navigation("ProfessionalPath");
                });
#pragma warning restore 612, 618
        }
    }
}
